[MURMUR]
ip="localhost"
port=6502

[MUMBLE]
default_name="MumbleLink par EliottBvl."
superuser_password="CHANGEME"
server_password="CHANGEMETOO"
public_ip="0.0.0.0"
first_port=64738

[SOCKET]
ip="127.0.0.1"
port=751

[WEB]
ip="127.0.0.1"
port=80

[AUTH]
api-key="CHANGEMETOO"

[LOG]
create=true
delete=true
create-user=true
mute=true
mute-all=true
unmute=true
unmute-all=true
move=true
move-all=true
set-admin-perms=true
set-player-perms=true
get-user-info=true
get-users-info=true